apiVersion: v1
kind: Pod
metadata:
  name: probe-test
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3

    readinessProbe:
      httpGet:
        path: /healthz
        port: 80
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3