apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
  - name: config-pod
    image: busybox:latest
    command: ["sh", "-c", "env && cat /etc/config/MAX_RETRIES && sleep 3600"]
    env:
      - name: LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: LOG_LEVEL
    ports:
    - containerPort: 80