apiVersion: v1
data:
  LOG_LEVEL: debug
  MAX_RETRIES: "5"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: app-config

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: config-pod
  name: config-pod
spec:
  containers:
    - image: busybox
      name: api-server
      resources: {}
      env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOG_LEVEL
      volumeMounts:
        - name: max-retries
          mountPath: "/etc/config/"
          readOnly: true
  volumes:
    - name: max-retries
      configMap:
        name: app-config
