apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
  - name: config-pod
    image: busybox:latest
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
    env:
      - name: LOG_LEVEL
        valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOG_LEVEL
    volumeMounts:
    - name: config
      mountPath: "/etc/config/"
  volumes:
  - name: config
    configMap:
      name: app-config
      items:
      - key: "MAX_RETRIES"
        path: "MAX_RETRIES"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  LOG_LEVEL: "debug"
  MAX_RETRIES: |
    MAX_RETRIES=5
