apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: custom-pod
  name: custom-pod
spec:
  containers:
    - image: alpine:latest
      name: custom-pod
      resources: {}
  nodeSelector:
    disk: ssd
