apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-app
  name: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-app
    spec:
      containers:
      - image: nginx:1.23
        name: nginx
        ports:
        - containerPort: 80
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1    
     maxSurge: 2