apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: critical-app
  name: critical-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: critical-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: critical-app
    spec:
      containers:
        - image: nginx
          name: nginx
          resources: {}
status: {}

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-critical
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: critical-app
