apiVersion: v1
kind: Pod
metadata:
  name: db-client
spec:
  containers:
  - name: mysql
    image: mysql:8
    env:
      - name: password
        valueFrom:
          secretKeyRef:
            name: db-secret             
            key: password

      - name: username
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: username

---

apiVersion: v1
data:
  password: U2VjdXJlUEBzczEyMw==
  username: ZGJfdXNlcg==
kind: Secret
metadata:
  creationTimestamp: null
  name: db-secret