apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  containers:
    - image: nginx
      name: nginx

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
  namespace: backend
spec:
  containers:
    - image: nginx
      name: nginx

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-external
  namespace: backend
spec:
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend
