apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: database
  labels:
    app: db-service
spec:
  ports:
  - port: 5432
  clusterIP: None
  selector:
    app: db-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-cluster
  namespace: database
spec:
  selector:
    matchLabels:
      app: db-cluster
  serviceName: "db-service"
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: db-cluster
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: db-cluster
        image: mysql:8
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123?mysql"
  volumeClaimTemplates:
  - metadata:
      name: db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 5Gi